apiVersion: apps/v1
kind: Deployment
metadata:
  name: carvilla
  labels:
    app: carvilla
spec:
  replicas: 3
  selector:
    matchLabels:
      app: carvilla
  template:
    metadata:
      labels:
        app: carvilla
    spec:
      containers:
      - name: carvilla
        image: sirony514/carvilla:0.0.1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: carvilla
spec:
  selector:
    app: carvilla
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
